command_timeout = 1000

[package]
disabled = true

[python]
format = '[${symbol}(${version})]($style)'

[git_status]
conflicted = 'ğŸ³'
# ahead = 'ğŸğŸ’¨'
# behind = 'ğŸ˜°'
# diverged = 'ğŸ˜µ'
up_to_date = ''
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[custom.desk]
when = ''' test "$DESK_NAME" '''
command = 'printf "${DESK_NAME}"'
format = ' ğŸ“:[$output]($style) '

[custom.ctx]
when = ''' test "$CTX" '''
command = 'printf "${CTX}"'
format = 'î®£:[$output]($style) '

[java]
disabled = true
